"""Add BloodBank table

Revision ID: 1bfb0bc7fe8c
Revises: 40a511f9459d
Create Date: 2026-04-13 21:30:28.126271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfb0bc7fe8c'
down_revision = '40a511f9459d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.String(length=10), nullable=False),
    sa.Column('units_available', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_bank_blood_type'), 'blood_bank', ['blood_type'], unique=True)
    op.create_index(op.f('ix_blood_bank_id'), 'blood_bank', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blood_bank_id'), table_name='blood_bank')
    op.drop_index(op.f('ix_blood_bank_blood_type'), table_name='blood_bank')
    op.drop_table('blood_bank')
    # ### end Alembic commands ###
