"""Add approval status

Revision ID: 40a511f9459d
Revises: fb814350383c
Create Date: 2026-04-13 21:06:39.440474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a511f9459d'
down_revision = 'fb814350383c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergies', sa.Column('approval_status', sa.String(length=20), nullable=True))
    op.add_column('conditions', sa.Column('approval_status', sa.String(length=20), nullable=True))
    op.add_column('devices', sa.Column('approval_status', sa.String(length=20), nullable=True))
    op.add_column('emergency_contacts', sa.Column('approval_status', sa.String(length=20), nullable=True))
    op.add_column('medications', sa.Column('approval_status', sa.String(length=20), nullable=True))
    op.add_column('patient_insurance', sa.Column('approval_status', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('approval_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'approval_status')
    op.drop_column('patient_insurance', 'approval_status')
    op.drop_column('medications', 'approval_status')
    op.drop_column('emergency_contacts', 'approval_status')
    op.drop_column('devices', 'approval_status')
    op.drop_column('conditions', 'approval_status')
    op.drop_column('allergies', 'approval_status')
    # ### end Alembic commands ###
