"""Add phone_number to user

Revision ID: 51cf6374d444
Revises: 1bfb0bc7fe8c
Create Date: 2026-04-13 22:14:44.338021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51cf6374d444'
down_revision = '1bfb0bc7fe8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_logs', 'details',
               existing_type=mysql.JSON(),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.alter_column('access_logs', 'details',
               existing_type=sa.String(length=2000),
               type_=mysql.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###
