"""schema_fixes

Revision ID: 81626c726411
Revises: 51cf6374d444
Create Date: 2026-04-18 07:20:31.370229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81626c726411'
down_revision = '51cf6374d444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_index(op.f('ix_incidents_incident_id'), 'incidents', ['incident_id'], unique=False)
    op.add_column('doctors', sa.Column('approval_status', sa.String(length=20), nullable=True))
    op.add_column('insurance_providers', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('insurance_providers', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('insurance_providers', sa.Column('address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurance_providers', 'address')
    op.drop_column('insurance_providers', 'website')
    op.drop_column('insurance_providers', 'contact_email')
    op.drop_column('doctors', 'approval_status')
    op.drop_index(op.f('ix_incidents_incident_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
