"""add resource and details to log

Revision ID: fb814350383c
Revises: fff214937e8b
Create Date: 2026-04-13 20:15:20.686442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb814350383c'
down_revision = 'fff214937e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_logs', sa.Column('resource', sa.String(length=255), nullable=True))
    op.add_column('access_logs', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_logs', 'details')
    op.drop_column('access_logs', 'resource')
    # ### end Alembic commands ###
