"""init

Revision ID: fff214937e8b
Revises: 
Create Date: 2026-04-12 06:55:41.103826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff214937e8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_index(op.f('ix_hospitals_hospital_id'), 'hospitals', ['hospital_id'], unique=False)
    op.create_table('insurance_providers',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('payer_phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_index(op.f('ix_insurance_providers_provider_id'), 'insurance_providers', ['provider_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'doctor', 'patient', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('access_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_access_logs_log_id'), 'access_logs', ['log_id'], unique=False)
    op.create_table('doctors',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_doctors_doctor_id'), 'doctors', ['doctor_id'], unique=False)
    op.create_table('patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('emergency_identifier', sa.String(length=50), nullable=False),
    sa.Column('blood_type', sa.String(length=10), nullable=True),
    sa.Column('emergency_contact_summary', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_patients_emergency_identifier'), 'patients', ['emergency_identifier'], unique=True)
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=False)
    op.create_table('allergies',
    sa.Column('allergy_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('allergy_name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('allergy_id')
    )
    op.create_index(op.f('ix_allergies_allergy_id'), 'allergies', ['allergy_id'], unique=False)
    op.create_table('conditions',
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('condition_name', sa.String(length=255), nullable=False),
    sa.Column('critical_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_index(op.f('ix_conditions_condition_id'), 'conditions', ['condition_id'], unique=False)
    op.create_table('devices',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_relationship', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_index(op.f('ix_emergency_contacts_contact_id'), 'emergency_contacts', ['contact_id'], unique=False)
    op.create_table('medications',
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('medication_id')
    )
    op.create_index(op.f('ix_medications_medication_id'), 'medications', ['medication_id'], unique=False)
    op.create_table('patient_insurance',
    sa.Column('patient_insurance_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('plan_type', sa.String(length=100), nullable=True),
    sa.Column('member_id', sa.String(length=100), nullable=True),
    sa.Column('group_number', sa.String(length=100), nullable=True),
    sa.Column('coverage_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['insurance_providers.provider_id'], ),
    sa.PrimaryKeyConstraint('patient_insurance_id')
    )
    op.create_index(op.f('ix_patient_insurance_patient_insurance_id'), 'patient_insurance', ['patient_insurance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_insurance_patient_insurance_id'), table_name='patient_insurance')
    op.drop_table('patient_insurance')
    op.drop_index(op.f('ix_medications_medication_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_emergency_contacts_contact_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_conditions_condition_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_allergies_allergy_id'), table_name='allergies')
    op.drop_table('allergies')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_emergency_identifier'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_doctors_doctor_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_access_logs_log_id'), table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_insurance_providers_provider_id'), table_name='insurance_providers')
    op.drop_table('insurance_providers')
    op.drop_index(op.f('ix_hospitals_hospital_id'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
